# Generated by Django 3.1 on 2021-06-17 06:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0004_client_deletion_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название Категории (ru)')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Название Категории (uz)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название Категории (en)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid_1c', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='UUID (1C)')),
                ('name', models.CharField(max_length=200, verbose_name='Название Продукта (ru)')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Название Продукта (uz)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название Продукта (en)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('measure', models.CharField(blank=True, default='шт', max_length=30, null=True, verbose_name='Ед. измерения')),
                ('price_for', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='Цена за')),
                ('reminder', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Остаток')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание (ru)')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Описание (uz)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание (en)')),
                ('employment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Применение')),
                ('size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Типоразмер')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель')),
                ('factory', models.CharField(blank=True, max_length=255, null=True, verbose_name='Завод')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Выберите картинку')),
                ('image_url_file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID картинки')),
                ('video_url_file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID видео')),
                ('show_bot', models.BooleanField(default=True, verbose_name='Показывать в боте')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.category', verbose_name='Идентификатор Категории')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('purchase_time', models.DateTimeField(auto_now_add=True, verbose_name='Время покупки')),
                ('phone_number', models.CharField(blank=True, max_length=70, null=True, verbose_name='Номер телефона')),
                ('order_status', models.CharField(choices=[('rejected', '❌ Отклонено'), ('awaiting_shipment', '🕔🚕 Ожидает отгрузки'), ('on_the_way', '🚕 В пути'), ('accepted', '✅ Принят')], max_length=50, verbose_name='Статус заказа')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Долгота (longitude)')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Широта (latitude)')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('type_of_payment', models.CharField(blank=True, choices=[('cash', '💵 Наличные'), ('terminal', '💳 Терминал')], max_length=50, null=True, verbose_name='Способ оплаты')),
                ('receiver', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя получателя')),
                ('successful', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('update_api', models.BooleanField(default=False, verbose_name='Обновить в API')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название Подкатегории (ru)')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Название Подкатегории (uz)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название Подкатегории (en)')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('user_id', models.BigIntegerField(default=1, editable=False, unique=True, verbose_name='ID Пользователя Телеграм')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя пользователя')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username Телеграм')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uz', 'Ўзбек'), ('en', 'English')], default='ru', max_length=2, verbose_name='Язык')),
                ('access', models.BooleanField(default=False, verbose_name='Доступ')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contractors.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usersmanage.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='usersmanage.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='usersmanage.item', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Список продуктов',
                'verbose_name_plural': 'Список продуктов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=models.SET(0), to='usersmanage.user', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usersmanage.subcategory', verbose_name='Идентификатор Подкатегории'),
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='usersmanage.item', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='usersmanage.user')),
            ],
            options={
                'verbose_name': 'Список продуктов (корзина)',
                'verbose_name_plural': 'Список продуктов (корзина)',
            },
        ),
    ]
