# Generated by Django 3.1 on 2021-10-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_act_sverki',
            field=models.BooleanField(default=False, verbose_name='Доступ к акт сверки'),
        ),
    ]
