# Generated by Django 3.1 on 2021-11-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0002_user_access_act_sverki'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.item', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Список продуктов (доп.)',
                'verbose_name_plural': 'Список продуктов (доп.)',
            },
        ),
    ]
