# Generated by Django 3.1 on 2021-11-03 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0003_additionorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionBasketItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.item', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.user')),
            ],
            options={
                'verbose_name': 'Список продуктов (доп. корзина)',
                'verbose_name_plural': 'Список продуктов (доп. корзина)',
            },
        ),
    ]
