# Generated by Django 3.1 on 2021-11-04 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0004_client_deletion_mark'),
        ('usersmanage', '0004_additionbasketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clients',
            field=models.ManyToManyField(related_name='clients', to='contractors.Client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='contractors.client', verbose_name='Клиент'),
        ),
    ]
