# Generated by Django 3.1 on 2021-11-05 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0006_remove_user_clients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionBasketItem',
        ),
    ]
