# Generated by Django 3.1 on 2021-11-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0007_delete_additionbasketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_group_of_counterparties',
            field=models.BooleanField(default=False, verbose_name='Группа контрагентов'),
        ),
    ]
