# Generated by Django 3.1 on 2021-11-22 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0004_client_deletion_mark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersmanage', '0008_user_access_group_of_counterparties'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Время редактирования')),
                ('user_id', models.BigIntegerField(db_index=True, default=1, editable=False, verbose_name='ID Пользователя Телеграм')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя пользователя')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username Телеграм')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uz', 'Ўзбек'), ('en', 'English')], default='ru', max_length=2, verbose_name='Язык')),
                ('access', models.BooleanField(default=False, verbose_name='Доступ')),
                ('access_act_sverki', models.BooleanField(default=False, verbose_name='Доступ к акт сверки')),
                ('access_group_of_counterparties', models.BooleanField(default=False, verbose_name='Группа контрагентов')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contractors.client', verbose_name='Клиент')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Пользователь',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
