# Generated by Django 3.1 on 2021-11-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0009_historicaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='load',
            field=models.BooleanField(default=False, verbose_name='Нагрузка'),
        ),
        migrations.AddField(
            model_name='item',
            name='running',
            field=models.BooleanField(default=False, verbose_name='Ходовой'),
        ),
    ]
