# Generated by Django 3.1 on 2021-12-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0010_auto_20211129_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование (ru)')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Наименование (uz)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Наименование (en)')),
                ('show_bot', models.BooleanField(default=True, verbose_name='Показывать в боте')),
            ],
            options={
                'verbose_name': 'Отзыв (основной)',
                'verbose_name_plural': 'Отзывы (основной)',
            },
        ),
    ]
