# Generated by Django 3.1 on 2021-12-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0011_mainreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.TextField(blank=True, null=True, verbose_name='Категория отзыва'),
        ),
    ]
