# Generated by Django 3.1 on 2022-01-17 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0013_auto_20220104_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_items', to='usersmanage.order'),
        ),
    ]
