# Generated by Django 3.1 on 2022-01-31 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0004_client_deletion_mark'),
        ('usersmanage', '0014_auto_20220117_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='choice_from_list_clients',
            field=models.BooleanField(default=False, verbose_name='Доступ к выбору клиента'),
        ),
        migrations.AddField(
            model_name='user',
            name='choice_from_list_clients',
            field=models.BooleanField(default=False, verbose_name='Доступ к выбору клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('new', '🆕 Новый'), ('rejected', '❌ Отклонено'), ('awaiting_shipment', '🕔🚕 Ожидает отгрузки'), ('on_the_way', '🚕 В пути'), ('accepted', '✅ Принят')], max_length=50, verbose_name='Статус заказа'),
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('access', models.BooleanField(default=False, verbose_name='Доступ')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.client', verbose_name='Клиент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Список контрагентов',
                'verbose_name_plural': 'Список контрагентов',
            },
        ),
    ]
