# Generated by Django 3.1 on 2022-01-31 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0015_auto_20220131_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='usersmanage.user', verbose_name='Пользователь'),
        ),
    ]
