# Generated by Django 3.1 on 2022-01-31 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0004_client_deletion_mark'),
        ('usersmanage', '0016_auto_20220131_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contractors.client', verbose_name='Клиент 1С'),
        ),
    ]
