# Generated by Django 3.1 on 2022-04-07 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0004_client_deletion_mark'),
        ('usersmanage', '0018_auto_20220221_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='contractors.client', verbose_name='Клиент'),
        ),
    ]
