# Generated by Django 3.1 on 2021-04-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='ru', max_length=2, unique=True, verbose_name='Язык')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Выберите картинку')),
                ('image_url_file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID картинки')),
                ('video_url_file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID видео')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Широта (latitude)')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Долгота (longitude)')),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='ru', max_length=2, unique=True, verbose_name='Язык')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Выберите картинку')),
                ('image_url_file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID картинки')),
                ('video_url_file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID видео')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Широта (latitude)')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Долгота (longitude)')),
            ],
        ),
    ]
