# Generated by Django 3.1 on 2021-04-10 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instruments_telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'Сообщение пользователю (О нас)', 'verbose_name_plural': 'Сообщение пользователю (О нас)'},
        ),
        migrations.AlterModelOptions(
            name='welcomemessage',
            options={'verbose_name': 'Сообщение пользователю (welcome)', 'verbose_name_plural': 'Сообщение пользователю (welcome)'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время редактирования'),
        ),
        migrations.AddField(
            model_name='welcomemessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='welcomemessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время редактирования'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='welcomemessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
