# Generated by Django 3.1 on 2021-04-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments_telegram', '0002_auto_20210410_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Выберите картинку'),
        ),
        migrations.AlterField(
            model_name='welcomemessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Выберите картинку'),
        ),
    ]
