# Generated by Django 3.1 on 2021-04-10 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments_telegram', '0003_auto_20210410_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welcomemessage',
            options={'verbose_name': 'Сообщение пользователю (Welcome)', 'verbose_name_plural': 'Сообщение пользователю (Welcome)'},
        ),
    ]
