# Generated by Django 3.1 on 2021-04-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments_telegram', '0005_auto_20210415_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='language',
            field=models.CharField(choices=[('ru', '🇷🇺 Русский'), ('uz', '🇺🇿 Ўзбек'), ('en', '🇺🇸 English')], default='ru', max_length=2, unique=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='welcomemessage',
            name='language',
            field=models.CharField(choices=[('ru', '🇷🇺 Русский'), ('uz', '🇺🇿 Ўзбек'), ('en', '🇺🇸 English')], default='ru', max_length=2, unique=True, verbose_name='Язык'),
        ),
    ]
