# Generated by Django 3.1 on 2021-04-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments_telegram', '0007_auto_20210415_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='id_1C',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID (1C)'),
        ),
    ]
