# Generated by Django 3.1 on 2021-04-28 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments_telegram', '0008_aboutus_id_1c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='id_1C',
        ),
    ]
