# Generated by Django 3.1 on 2021-05-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments_telegram', '0011_auto_20210508_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='skills',
        ),
    ]
