# Generated by Django 3.1 on 2021-05-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments_telegram', '0012_remove_person_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(related_name='persons', through='instruments_telegram.PersonSkill', to='instruments_telegram.Skill'),
        ),
    ]
