# Generated by Django 3.1 on 2021-05-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments_telegram', '0014_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='skills',
        ),
        migrations.AlterUniqueTogether(
            name='personskill',
            unique_together={('person', 'skill')},
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
