# Generated by Django 3.1 on 2021-05-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments_telegram', '0015_auto_20210508_2209'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personskill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='personskill',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personskill',
            name='skill',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonSkill',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
