# Generated by Django 3.1 on 2022-01-17 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersmanage', '0014_auto_20220117_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restrict_Users_TGBOT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Наименование')),
                ('enabled', models.BooleanField(default=False, verbose_name='Использование')),
                ('days', models.IntegerField(default=0, verbose_name='Количество дней неиспользования заказом')),
            ],
            options={
                'verbose_name': 'Ограничение пользователей (ТГ БОТ)',
                'verbose_name_plural': 'Ограничения пользователей (ТГ БОТ)',
            },
        ),
        migrations.CreateModel(
            name='Restrict_Users_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('disabled', models.BooleanField(default=False, verbose_name='Не актив')),
                ('restrict_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disabled_users', to='constants.restrict_users_tgbot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('restrict_users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constants.restrict_users_tgbot')),
            ],
            options={
                'verbose_name': 'Константа',
                'verbose_name_plural': 'Константы',
            },
        ),
    ]
