# Generated by Django 3.1 on 2022-01-17 19:40

from django.db import migrations, models
import django.db.models.deletion
import django_project.telegrambot.constants.models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constants',
            name='restrict_users',
            field=models.ForeignKey(blank=True, default=django_project.telegrambot.constants.models.Restrict_Users_TGBOT, null=True, on_delete=django.db.models.deletion.CASCADE, to='constants.restrict_users_tgbot'),
        ),
    ]
