# Generated by Django 3.1 on 2022-01-17 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0002_auto_20220118_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constants',
            name='restrict_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constants.restrict_users_tgbot'),
        ),
    ]
