# Generated by Django 3.1 on 2022-02-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0003_auto_20220118_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='constants',
            name='login_1c',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Логин (1С)'),
        ),
        migrations.AddField(
            model_name='constants',
            name='password_1c',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Пароль (1С)'),
        ),
        migrations.AddField(
            model_name='constants',
            name='url_to_act_sverki',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка на акт сверки (API)'),
        ),
    ]
