# Generated by Django 3.1 on 2022-02-19 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0004_auto_20220219_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('login_1c', models.CharField(blank=True, default='', max_length=100, verbose_name='Логин (1С)')),
                ('password_1c', models.CharField(blank=True, default='', max_length=100, verbose_name='Пароль (1С)')),
                ('url_to_act_sverki', models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка на акт сверки (API)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='constants',
            name='login_1c',
        ),
        migrations.RemoveField(
            model_name='constants',
            name='password_1c',
        ),
        migrations.RemoveField(
            model_name='constants',
            name='url_to_act_sverki',
        ),
        migrations.AlterField(
            model_name='constants',
            name='restrict_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constants.restrict_users_tgbot'),
        ),
        migrations.AddField(
            model_name='constants',
            name='setting_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constants.settingsapi'),
        ),
    ]
