# Generated by Django 3.1 on 2022-02-19 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0005_auto_20220219_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingsapi',
            options={'verbose_name': 'Настройка (API)', 'verbose_name_plural': 'Настройки (API)'},
        ),
        migrations.AddField(
            model_name='settingsapi',
            name='name',
            field=models.CharField(default='Hello', max_length=255, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='constants',
            name='setting_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constants.settingsapi', verbose_name='Настройка (API)'),
        ),
    ]
