# Generated by Django 3.1 on 2022-02-21 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0007_auto_20220221_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('name_uz', models.CharField(max_length=255, verbose_name='Наименование (uz)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Наименование (en)')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.AddField(
            model_name='constants',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constants.currency', verbose_name='Валюта'),
        ),
    ]
