# Generated by Django 3.1 on 2022-03-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0010_auto_20220225_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsapi',
            name='type_of_act_sverki',
            field=models.CharField(blank=True, choices=[('text', 'Текст'), ('file_pdf', 'Файл (pdf)')], default='file_pdf', max_length=255, verbose_name='Тип акта сверки'),
        ),
    ]
