# Generated by Django 3.1 on 2022-03-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0018_auto_20220311_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='constants',
            name='timeout_cancel_order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Таймаут отказа заказа'),
        ),
    ]
