# Generated by Django 3.1 on 2022-04-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0019_constants_timeout_cancel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='constants',
            name='access_bot',
            field=models.BooleanField(default=False, verbose_name='По-умолчанию доступ к боту'),
        ),
    ]
