# Generated by Django 3.1 on 2021-05-09 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contractors.branch', verbose_name='Идентификатор Филиал'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='12', max_length=200, verbose_name='Наименование'),
            preserve_default=False,
        ),
    ]
